export type Locale = 'zh' | 'en';

export const localePaths = { zh: '/', en: '/en/' } as const;
export const myTestsPaths = { zh: '/my-tests/', en: '/en/my-tests/' } as const;

export const english: Record<string, string> = {
  '返回首页': 'Back to home',
  '我的测试': 'My tests',
  '我的鹈鹕测试集锦': 'My pelican test collection',
  '我的鹈鹕测试集锦 | Pelican Test': 'My pelican test collection | Pelican Test',
  '记录我的鹈鹕骑行测试，浏览不同模型的作品、日期和原始提示词，打开完整演示。':
    'Browse my pelican cycling tests, with model names, dates, original prompts, and complete demos.',
  '我用不同模型生成的鹈鹕骑行作品，持续收集中。':
    'My pelican cycling experiments with different models. More to come.',
  '跳到测试集锦': 'Skip to test collection',
  '鹈鹕骑车 SVG 动画': 'Pelican cycling SVG animation',
  '海边骑行场景，支持暂停、三档速度和车铃。':
    'A seaside ride with playback controls, three speeds, and a bicycle bell.',
  '系着红围巾的鹈鹕骑着绿色自行车，沿着海边前进':
    'A pelican wearing a red scarf rides a green bicycle along the coast',
  '模型': 'Model',
  '日期': 'Date',
  '打开测试': 'Open test',
  '新标签页': 'new tab',
  '打开完整演示': 'Open full demo',
  '浏览鹈鹕测试时间轴': 'Browse the pelican test timeline',
  '固定提示词': 'Standard prompt',
  '回顾样本': 'Retrospective sample',
  '混合口径': 'Mixed criteria',
  '动画变体': 'Animation variant',
  '待确认': 'Unconfirmed',
  '首轮 16 个模型': 'Initial 16 models',
  '多数模型只画出了鸟或几何块': 'Most models drew only a bird or geometric shapes',
  '模型通常能生成 SVG，也知道鸟或轮子大概长什么样，但无法组织出骑自行车的完整关系。':
    'Models could usually generate SVG and approximate birds or wheels, but they could not assemble a coherent bicycle-riding scene.',
  'Claude 3 Opus 生成的鹈鹕和两轮自行车，主体与车架连接仍然错乱':
    'A pelican and two-wheeled bicycle generated by Claude 3 Opus, with the rider and frame still connected incorrectly',
  'Claude 3 Haiku 生成的橙色抽象鸟形和简化自行车':
    'An abstract orange bird and simplified bicycle generated by Claude 3 Haiku',
  'Claude 3.5 Sonnet 2024 年 6 月版生成的简化鹈鹕和几何车架':
    'A simplified pelican and geometric frame generated by the June 2024 Claude 3.5 Sonnet',
  'Claude 3.5 Sonnet 2024 年 10 月升级版生成的鹈鹕和自行车尝试':
    'A pelican-and-bicycle attempt generated by the October 2024 Claude 3.5 Sonnet',
  'GPT-4o 生成的一只孤立的鸟': 'An isolated bird generated by GPT-4o',
  'o1-preview 生成的鸟和一条竖线，没有形成自行车':
    'A bird and vertical line generated by o1-preview, without a bicycle',
  'Gemini 1.5 Flash-002 生成的黄色几何块':
    'Yellow geometric shapes generated by Gemini 1.5 Flash-002',
  'Gemini 1.5 Flash-8B 生成的抽象黄色图形':
    'An abstract yellow figure generated by Gemini 1.5 Flash-8B',
  'Llama 3.1 70B 生成的抽象轮状图案':
    'An abstract wheel-like pattern generated by Llama 3.1 70B',
  '首轮测试': 'Initial test',
  '原始样本仓库': 'Original sample repository',
  'Claude 3 发布': 'Claude 3 announcement',
  'Claude 3.5 首发': 'Claude 3.5 launch',
  'Claude 3.5 升级版': 'Claude 3.5 upgrade',
  '推理变长，构图没有同步解决': 'Longer reasoning did not fix composition',
  '较长的推理过程最终仍得到抽象鸟形。这个样本很早就说明，更多推理 token 不保证更好的空间构图。':
    'A longer reasoning process still produced an abstract bird. This early sample showed that more reasoning tokens do not guarantee better spatial composition.',
  'QwQ 32B Preview 生成的抽象蓝色鸟形':
    'An abstract blue bird generated by QwQ 32B Preview',
  'X 原帖': 'Original post on X',
  'Qwen 归档': 'Qwen archive',
  '第一次明显形成完整场景': 'The first clearly complete scene',
  '主体、两个车轮、车架和地面同时出现。画面还不精确，但已经从识别对象跨到组织场景。':
    'The subject, two wheels, frame, and ground all appear together. The image is still imprecise, but it moves from recognizing objects to composing a scene.',
  'Gemini exp-1206 生成的鹈鹕骑两轮自行车场景':
    'A pelican riding a two-wheeled bicycle generated by Gemini exp-1206',
  '博客记录': 'Blog post',
  '完整场景开始成为常态': 'Complete scenes started becoming routine',
  '鹈鹕、车轮和车架已经在同一画面里，但主体更像叠放，接触关系仍然薄弱。':
    'The pelican, wheels, and frame now share one image, but they look stacked together and their contact relationships remain weak.',
  'DeepSeek V3 的鹈鹕和近似自行车结构':
    'DeepSeek V3\'s pelican with an approximate bicycle structure',
  '六个月回顾': 'Six-month retrospective',
  '对象更清楚，物理关系仍脆弱': 'Clearer objects, fragile physical relationships',
  '鹈鹕和自行车更容易辨认，细节也更多，但鸟、车把和脚踏之间仍缺少可信连接。':
    'The pelican and bicycle are easier to recognize and more detailed, but the bird, handlebars, and pedals still lack believable connections.',
  'DeepSeek R1 生成的鹈鹕和近似自行车车架':
    'A pelican and approximate bicycle frame generated by DeepSeek R1',
  '首发测试': 'Launch test',
  '推理模式带来两次可比结果': 'Reasoning mode produced two comparable results',
  '普通模式与 thinking 模式都画出了完整主体和自行车元素，但局部仍有重复、错位和堆叠。':
    'Both standard and thinking modes drew a complete subject and bicycle elements, but parts were still duplicated, misaligned, or stacked.',
  '普通模式': 'Standard mode',
  'Claude 3.7 Sonnet 普通模式生成的鹈鹕与自行车元素':
    'Pelican and bicycle elements generated by Claude 3.7 Sonnet in standard mode',
  'Thinking 模式': 'Thinking mode',
  'Claude 3.7 Sonnet thinking 模式生成的鹈鹕与自行车元素':
    'Pelican and bicycle elements generated by Claude 3.7 Sonnet in thinking mode',
  '双模式测试': 'Two-mode test',
  'Anthropic 发布': 'Anthropic announcement',
  '骑车关系开始稳定': 'The riding relationship started to stabilize',
  '问题从有没有自行车，转向车架是否合理、脚是否真正踩在踏板上。':
    'The question shifted from whether there was a bicycle to whether the frame made sense and the feet truly met the pedals.',
  'Gemini 2.5 Pro 生成的鹈鹕和自行车完整场景':
    'A complete pelican-and-bicycle scene generated by Gemini 2.5 Pro',
  '同代两档模型首次并排': 'Two tiers of one generation compared side by side',
  'Sonnet 4 的自行车更完整，Opus 4 的车轮缺少辐条。两者都能完成场景，但旗舰档位并没有在这次单样本中明显胜出。':
    'Sonnet 4 produced the more complete bicycle, while Opus 4 omitted wheel spokes. Both completed the scene, but the flagship did not clearly win this single sample.',
  'Claude Sonnet 4 生成的鹈鹕骑自行车，车架和轮辐较完整':
    'A pelican riding a bicycle generated by Claude Sonnet 4, with a relatively complete frame and spokes',
  'Claude Opus 4 生成的鹈鹕骑自行车，车轮缺少辐条':
    'A pelican riding a bicycle generated by Claude Opus 4, with missing wheel spokes',
  '发布会实测': 'Live launch test',
  '进入较完整的骑行构图': 'A more complete riding composition',
  '红色车架、两个轮子和车把相互连接，鹈鹕姿态也更接近骑乘。':
    'The red frame, two wheels, and handlebars connect to one another, and the pelican\'s pose looks more like riding.',
  'Gemini 2.5 Pro Preview 生成的鹈鹕骑红色自行车':
    'A pelican riding a red bicycle generated by Gemini 2.5 Pro Preview',
  '鸟形进步，自行车仍是短板': 'The bird improved; the bicycle remained the weak point',
  '线稿里的喙和脚踏关系更清楚，但车架形状依然不合理，说明点版本升级没有稳定解决空间结构。':
    'The line drawing clarifies the beak and pedal relationship, but the frame is still implausible, showing that the point release did not reliably solve spatial structure.',
  'Claude Opus 4.1 生成的线稿鹈鹕骑自行车，车架形状仍不规则':
    'A line-art pelican riding a bicycle generated by Claude Opus 4.1, with an irregular frame',
  '发布日实测': 'Launch-day test',
  'GPT-5 系列': 'GPT-5 family',
  '自行车结构显著改善': 'Bicycle structure improved substantially',
  '车架、辐条、脚踏、腿部位置和整体比例都明显进步。小模型也能完成场景，但细节并不按规模单调变化。':
    'The frame, spokes, pedals, leg placement, and overall proportions all improved. Smaller models could also complete the scene, though detail did not improve monotonically with model size.',
  'GPT-5 生成的结构完整自行车和正在踩踏的鹈鹕':
    'A structurally complete bicycle and pedaling pelican generated by GPT-5',
  'GPT-5 mini 生成的鹈鹕骑自行车': 'A pelican riding a bicycle generated by GPT-5 mini',
  'GPT-5 nano 生成的鹈鹕骑自行车': 'A pelican riding a bicycle generated by GPT-5 nano',
  'Thinking 与普通模式各有缺陷': 'Thinking and standard modes each had flaws',
  '两次结果都能认出鹈鹕和自行车，但构件连接仍不可靠。Thinking 没有在这次单样本里带来稳定的结构优势。':
    'Both results show a recognizable pelican and bicycle, but the component connections remain unreliable. Thinking provided no consistent structural advantage in this single sample.',
  'Thinking 开启': 'Thinking on',
  'Claude Sonnet 4.5 开启 thinking 后生成的鹈鹕骑自行车':
    'A pelican riding a bicycle generated by Claude Sonnet 4.5 with thinking on',
  'Thinking 关闭': 'Thinking off',
  'Claude Sonnet 4.5 关闭 thinking 后生成的鹈鹕骑自行车':
    'A pelican riding a bicycle generated by Claude Sonnet 4.5 with thinking off',
  '轻量模型也能完成完整场景': 'Lightweight models could complete the scene too',
  '圆润的鸟形、两个车轮和地面同时出现。主体更像一般鸟类，但低成本档位已经跨过“完整构图”门槛。':
    'A rounded bird, two wheels, and ground appear together. The subject looks like a generic bird, but the lower-cost tier crossed the complete-composition threshold.',
  'Claude Haiku 4.5 生成的圆润鸟形骑自行车场景':
    'A rounded bird riding a bicycle generated by Claude Haiku 4.5',
  '细化要求改善物种特征与车架':
    'More detailed instructions improved species features and the frame',
  '原始提示词下鹈鹕朝向和车架仍有问题；加入繁殖羽、喉囊等要求后，鸟种特征与车架都明显改善，因此单独标记为混合口径。':
    'With the original prompt, the pelican orientation and frame still had problems. Adding breeding plumage and throat-pouch requirements improved both, so the result is marked as mixed criteria.',
  '原始提示词 · high': 'Original prompt · high',
  'Claude Opus 4.5 使用原始提示词生成的鹈鹕骑自行车，车架方向存在问题':
    'A pelican riding a bicycle generated by Claude Opus 4.5 from the original prompt, with an incorrectly oriented frame',
  '增强提示词': 'Enhanced prompt',
  'Claude Opus 4.5 使用增强提示词生成的繁殖羽鹈鹕和更完整自行车':
    'A breeding-plumage pelican and more complete bicycle generated by Claude Opus 4.5 from the enhanced prompt',
  '两种提示词实测': 'Two-prompt test',
  '基础任务与细节任务分轨': 'Base and detail tasks split into separate tracks',
  '基础提示词已经能生成完整结果。增强提示词增加鸟种、羽毛和喉囊要求，两者不应直接排名。':
    'The base prompt already produces a complete result. The enhanced prompt adds species, plumage, and throat-pouch requirements, so the two should not be ranked directly.',
  '原始提示词': 'Original prompt',
  'GPT-5.2 使用原始提示词生成的鹈鹕骑自行车':
    'A pelican riding a bicycle generated by GPT-5.2 from the original prompt',
  'GPT-5.2 使用增强提示词生成的加州褐鹈鹕骑自行车':
    'A California brown pelican riding a bicycle generated by GPT-5.2 from the enhanced prompt',
  '鹈鹕细节成熟，车架仍略扭曲': 'Mature pelican detail, a slightly distorted frame',
  '喙、喉囊和羽毛已经很像鹈鹕，整体观感明显成熟；自行车基本成立，但车架几何仍有轻微错位。':
    'The beak, throat pouch, and feathers now look convincingly pelican-like. The bicycle mostly works, though its frame geometry remains slightly misaligned.',
  'Claude Opus 4.6 生成的羽毛细节丰富的鹈鹕骑自行车，车架略有扭曲':
    'A richly feathered pelican riding a bicycle generated by Claude Opus 4.6, with a slightly distorted frame',
  '完整但带着稳定的怪异细节': 'Complete, but with consistently strange details',
  '两次尝试都给鹈鹕加了礼帽。展示样本的鸟喙之间多出一根线，车架也发生弯折，完整性不等于关系正确。':
    'Both attempts gave the pelican a top hat. The shown sample adds a stray line between the beak halves and bends the frame, proving completeness is not the same as correct relationships.',
  'Claude Sonnet 4.6 生成的戴礼帽鹈鹕骑自行车，车架弯折且鸟喙间有多余连线':
    'A top-hatted pelican riding a bicycle generated by Claude Sonnet 4.6, with a bent frame and stray line across the beak',
  '复杂约束继续增加': 'The constraints kept getting more complex',
  '原始提示词用于纵向比较，增强提示词测试羽毛、喉囊、姿势和场景细节。':
    'The original prompt supports longitudinal comparison, while the enhanced prompt tests plumage, throat pouch, pose, and scene detail.',
  'Gemini 3.1 Pro 使用原始提示词生成的鹈鹕骑自行车':
    'A pelican riding a bicycle generated by Gemini 3.1 Pro from the original prompt',
  'Gemini 3.1 Pro 使用增强提示词生成的细节版鹈鹕骑自行车':
    'A more detailed pelican riding a bicycle generated by Gemini 3.1 Pro from the enhanced prompt',
  'GPT-5.4 家族': 'GPT-5.4 family',
  '推理等级并不单调决定画质':
    'Reasoning level did not determine image quality monotonically',
  '同一家族的模型和推理等级组成对照矩阵。高推理通常有帮助，但单次画面并不保证更好。':
    'Models and reasoning levels from one family form a comparison matrix. More reasoning often helps, but does not guarantee a better single image.',
  '模型与推理等级矩阵': 'Model and reasoning-level matrix',
  'GPT-5.4 家族在多档推理等级下的鹈鹕测试矩阵':
    'A pelican-test matrix of the GPT-5.4 family across multiple reasoning levels',
  '家族对比': 'Family comparison',
  'GPT-5.4 首测': 'First GPT-5.4 test',
  '两次尝试都没修好自行车': 'Neither attempt fixed the bicycle',
  '默认与 max thinking 的鹈鹕都可以辨认，但车架分别以不同方式失真。更多推理没有在这次测试里解决结构问题。':
    'Both default and max-thinking results show recognizable pelicans, but their frames fail in different ways. More reasoning did not solve the structural problem in this test.',
  '默认推理': 'Default reasoning',
  'Claude Opus 4.7 默认推理生成的回头鹈鹕和错误自行车车架':
    'A backward-looking pelican and incorrect bicycle frame generated by Claude Opus 4.7 with default reasoning',
  'Claude Opus 4.7 max thinking 生成的鹈鹕和另一种错误自行车车架':
    'A pelican and another incorrect bicycle frame generated by Claude Opus 4.7 with max thinking',
  '双次测试': 'Two-run test',
  '本地小模型跨过实用门槛': 'A small local model crossed the practical threshold',
  '约 17GB 的本地模型已经画出完整车架、辐条、车把和踩踏姿势，进步不再只属于大型云端模型。':
    'A roughly 17GB local model drew a complete frame, spokes, handlebars, and pedaling pose. Progress was no longer limited to large cloud models.',
  'Qwen 3.6 27B 本地运行': 'Qwen 3.6 27B running locally',
  'Qwen 3.6 27B 本地模型生成的鹈鹕骑红色自行车':
    'A pelican riding a red bicycle generated by the local Qwen 3.6 27B model',
  '本地测试': 'Local test',
  '五档推理展示从鸭到鹈鹕': 'Five reasoning levels ranged from duck to pelican',
  'low、medium、high 更像鸭或鹭，xhigh 才稳定出现鹈鹕特征，max 的鸟形与自行车最完整，也付出了最高的输出成本。':
    'Low, medium, and high looked more like ducks or herons. Pelican features became reliable at xhigh, while max produced the most complete bird and bicycle at the highest output cost.',
  'Claude Opus 4.8 low 推理生成的鸭形鸟骑自行车':
    'A duck-like bird riding a bicycle generated by Claude Opus 4.8 at low reasoning',
  'Claude Opus 4.8 medium 推理生成的鹭形鸟骑自行车':
    'A heron-like bird riding a bicycle generated by Claude Opus 4.8 at medium reasoning',
  'Claude Opus 4.8 high 推理生成的鸭形鸟骑自行车':
    'A duck-like bird riding a bicycle generated by Claude Opus 4.8 at high reasoning',
  'Claude Opus 4.8 xhigh 推理生成的鹈鹕骑黑色自行车':
    'A pelican riding a black bicycle generated by Claude Opus 4.8 at xhigh reasoning',
  'Claude Opus 4.8 max 推理生成的鹈鹕骑红色自行车完整场景':
    'A complete pelican-riding-a-red-bicycle scene generated by Claude Opus 4.8 at max reasoning',
  '五档推理测试': 'Five-level reasoning test',
  '五档推理差异不再只是细节': 'Five reasoning levels differed by more than detail',
  '同一个固定提示词下，五档 effort 在造型、结构和输出成本上形成明显梯度；high 的 token 反而少于 medium，说明推理预算仍不是线性旋钮。':
    'With one fixed prompt, five effort levels formed a clear gradient in shape, structure, and output cost. High used fewer tokens than medium, showing that reasoning budget is not a linear dial.',
  'Claude Fable 5 low 推理生成的鹈鹕骑自行车':
    'A pelican riding a bicycle generated by Claude Fable 5 at low reasoning',
  'Claude Fable 5 medium 推理生成的鹈鹕骑自行车':
    'A pelican riding a bicycle generated by Claude Fable 5 at medium reasoning',
  'Claude Fable 5 high 推理生成的鹈鹕骑自行车':
    'A pelican riding a bicycle generated by Claude Fable 5 at high reasoning',
  'Claude Fable 5 xhigh 推理生成的鹈鹕骑自行车':
    'A pelican riding a bicycle generated by Claude Fable 5 at xhigh reasoning',
  'Claude Fable 5 max 推理生成的鹈鹕骑自行车':
    'A pelican riding a bicycle generated by Claude Fable 5 at max reasoning',
  '从静态构图进入动画 SVG': 'From static composition to animated SVG',
  '画面结构已经很完整，并且能生成动画。新的难点变成车轮转动时，脚能否持续跟随踏板。':
    'The scene structure is already complete and can be animated. The new challenge is keeping the feet on the pedals as the wheels turn.',
  'GLM 5.2 动画 SVG': 'GLM 5.2 animated SVG',
  'GLM 5.2 生成的动画鹈鹕骑自行车 SVG':
    'An animated SVG of a pelican riding a bicycle generated by GLM 5.2',
  '自行车成立，物种却退成了鹅':
    'The bicycle worked, but the species regressed into a goose',
  '车轮、车架和抓住车把的动作已经连贯，但主体更像白鹅。结构能力成熟后，物种辨识仍会独立失手。':
    'The wheels, frame, and grip on the handlebars are coherent, but the subject looks more like a white goose. Species recognition can still fail independently after structure matures.',
  'Claude Sonnet 5 生成的白鹅形鸟骑自行车':
    'A white goose-like bird riding a bicycle generated by Claude Sonnet 5',
  'GPT-5.6 家族': 'GPT-5.6 family',
  '同一家族内部仍有明显差异': 'Large differences remained within one model family',
  'Luna、Terra、Sol 和多档推理等级组成九宫格，展示模型档位、推理预算与采样的共同影响。':
    'Luna, Terra, Sol, and multiple reasoning levels form a 3×3 grid showing the combined effects of model tier, reasoning budget, and sampling.',
  'GPT-5.6 九宫格': 'GPT-5.6 3×3 grid',
  'GPT-5.6 Luna Terra Sol 在多档推理等级下的结果矩阵':
    'A result matrix for GPT-5.6 Luna, Terra, and Sol across multiple reasoning levels',
  '结果更完整，测试开始失去区分度':
    'Results improved as the test lost discriminating power',
  '场景已经相当连贯，但测试无法代表代理能力和工具调用等差异，也开始面临过度推理和成本问题。':
    'The scene is quite coherent, but the test cannot represent differences in agent capabilities or tool use, and now faces over-reasoning and cost issues.',
  'Kimi K3 生成的完整鹈鹕骑自行车场景':
    'A complete pelican-riding-a-bicycle scene generated by Kimi K3',
  '测试与反思': 'Test and reflection',
  '两次生成暴露渲染兼容性差异':
    'Two generations exposed rendering compatibility differences',
  '第一版用 SVG use 元素复用轮组，Simon 当时记录为“车轮缺失”，在本站现代浏览器中会显示；第二版改为显式车轮，构图也更稳。':
    'The first version reused wheels with SVG use elements. Simon recorded them as missing, though they render in modern browsers here. The second used explicit wheels and a steadier composition.',
  '第一次 · 复用轮组': 'First attempt · reused wheelset',
  'Claude Opus 5 第一次生成的鹈鹕骑红色自行车 SVG，轮组通过 SVG use 元素复用':
    'Claude Opus 5\'s first SVG of a pelican riding a red bicycle, with wheels reused through SVG use elements',
  '第二次 · 显式轮组': 'Second attempt · explicit wheels',
  'Claude Opus 5 第二次生成的鹈鹕骑红色自行车 SVG，车轮和车架完整':
    'Claude Opus 5\'s second SVG of a pelican riding a red bicycle, with complete wheels and frame',
  '两次测试': 'Two tests',
  '17GB 本地模型继续逼近前沿效果': 'A 17GB local model moved closer to frontier results',
  'xhigh 推理得到结构完整的结果，关闭推理则明显松散，直观显示效果、等待时间和本地资源之间的取舍。':
    'Xhigh reasoning produced a structurally complete result, while disabling reasoning made the composition much looser, exposing the tradeoff among quality, wait time, and local resources.',
  'xhigh 推理': 'xhigh reasoning',
  'Qwen 3.8 27B 使用 xhigh 推理生成的鹈鹕骑红色自行车':
    'A pelican riding a red bicycle generated by Qwen 3.8 27B with xhigh reasoning',
  '关闭推理': 'Reasoning off',
  'Qwen 3.8 27B 关闭推理后的较松散构图':
    'A looser composition from Qwen 3.8 27B with reasoning disabled',
  '未公开新模型': 'Undisclosed new model',
  '效果很好，但模型身份待确认': 'A strong result from an unconfirmed model',
  '原帖没有给出模型名称，讨论中也提到可能见过该测试。这里只展示实际结果，不据此判断排名。':
    'The original post did not name the model, and the discussion suggested it may have seen the test before. Only the result is shown here, without ranking it.',
  'X 视频样本': 'Video sample on X',
  '未公开模型生成的鹈鹕骑自行车动画':
    'An animation of a pelican riding a bicycle generated by an undisclosed model',
  '全部': 'All',
  '外观主题': 'Color theme',
  '浅色': 'Light',
  '深色': 'Dark',
  '跳到时间轴': 'Skip to timeline',
  '返回页面顶部': 'Back to top',
  '主导航': 'Primary navigation',
  '时间轴': 'Timeline',
  '比较口径': 'Method',
  '原始归档': 'Source archive',
  '大模型 SVG 能力演进': 'LLM SVG capability evolution',
  '同一提示词，看见两年进步': 'One prompt, two years of progress',
  '查看时间轴': 'Explore the timeline',
  '了解测试': 'About the test',
  '2024 年 Claude 3.5 Sonnet 的简化鸟形，与 2026 年 Qwen 3.8 27B 的完整鹈鹕骑自行车对比':
    'A comparison between the simplified bird from Claude 3.5 Sonnet in 2024 and the complete pelican riding a bicycle from Qwen 3.8 27B in 2026',
  '拖动对比 2024 与 2026': 'Drag to compare 2024 and 2026',
  '直接拖动图片，或使用方向键': 'Drag the image or use the arrow keys',
  '收录范围': 'Coverage',
  '时间轴起点': 'Timeline begins',
  '代表节点': 'Milestones',
  '实图与视频': 'Images and video',
  '当前更新': 'Latest update',
  '从“画出来”到“关系正确”': 'From drawing objects to getting relationships right',
  '选择年份，查看模型如何逐步解决对象、结构、接触关系和运动。':
    'Choose a year to see how models gradually solved objects, structure, contact, and motion.',
  '按年份筛选': 'Filter by year',
  '如何读这条时间轴': 'How to read this timeline',
  '它适合感受变化，不替代系统评测。四条记录规则避免把不同任务混成排行榜。':
    'It reveals the direction of change, but does not replace systematic evaluation. These rules keep different tasks from becoming a false leaderboard.',
  '固定提示词作为主线': 'Use the fixed prompt as the main thread',
  '主线统一使用 “Generate an SVG of a pelican riding a bicycle”。':
    'The main thread always uses “Generate an SVG of a pelican riding a bicycle.”',
  '增强提示词单独标记': 'Mark enhanced prompts separately',
  '加入鸟种、羽毛、背景等要求后，任务已经变化，不能直接横向排名。':
    'Adding requirements for species, plumage, or background changes the task, so the results should not be ranked directly.',
  '动画变体单独标记': 'Mark animation variants separately',
  '动画 SVG 还要处理时间与运动关系，难度不同于静态结果。':
    'Animated SVG must also handle time and motion, making it a different challenge from static output.',
  '未知模型不做结论': 'Draw no conclusions from unknown models',
  '只有结果、没有模型和运行信息的样本保留展示，但不参与能力判断。':
    'Samples with a result but no model or run information remain visible, but do not inform capability judgments.',
  'Claude 覆盖按可追溯样本': 'Include Claude models only when samples are traceable',
  'Claude 3 Sonnet、Claude 3.5 Haiku 与 Mythos 5 暂未找到可追溯的同提示词原图，因此不补空白节点。':
    'No traceable original image from the same prompt has been found for Claude 3 Sonnet, Claude 3.5 Haiku, or Mythos 5, so no placeholder milestones are added.',
  '测试正在趋于饱和。': 'The test is becoming saturated.',
  '它公开时间越长，越容易受样本挑选、随机性和训练数据影响。Simon 也认为它与综合能力的相关性已经减弱。':
    'The longer it remains public, the more it is affected by sample selection, randomness, and training data. Simon also believes its correlation with general capability has weakened.',
  '阅读 Simon 的反思': 'Read Simon\'s reflection',
  '资料整理至 2026-08-27。结果版权归原作者与发布者所有。':
    'Research compiled through 2026-08-27. Results remain the property of their original authors and publishers.',
  '查看完整来源归档': 'View the complete source archive',
  '图片预览': 'Image preview',
  '原始测试结果': 'Original test result',
  '预览导航': 'Preview navigation',
  '上一张': 'Previous',
  '下一张': 'Next',
  '关闭': 'Close',
  '打开原图': 'Open original image',
  '鹈鹕测试时间轴 | 大模型 SVG 能力演进':
    'Pelican Test Timeline | LLM SVG Capability Evolution',
  '用同一句 SVG 提示词，直观浏览 2024 到 2026 年不同大模型的实际效果演进。':
    'See how real outputs from different language models evolved from 2024 to 2026 using the same SVG prompt.',
};

export const translate = (locale: Locale, text: string) =>
  locale === 'en' ? (english[text] ?? text) : text;
